// <auto-generated />
namespace IP_NTier.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class extenduserwithcreatedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extenduserwithcreatedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201804302126159_extend user with createdOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
